# Generated by Django 5.2.8 on 2025-11-18 15:54

import attendify.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendances_attenda_81a928_idx',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='is_reusable',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='max_scans',
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='class_schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='attendify.classschedule'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='scan_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[attendify.models.validate_phone_number]),
        ),
    ]
