# Generated by Django 5.2.6 on 2025-09-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendify', '0002_alter_classschedule_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
