# Generated by Django 5.2.7 on 2025-10-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendify', '0003_alter_qrcode_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit_requirements',
            field=models.PositiveIntegerField(default=120, help_text='Total credit hours required for course completion'),
        ),
    ]
