# Generated by Django 5.2.7 on 2025-10-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendify', '0004_course_credit_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
